### PR TITLE
Iain has added style

### PR DESCRIPTION
**Pull request by imcwhinnie**
Iain thinks that you need some style big time. HO HO XD this is gonna be good

### CODE REVIEW

**Comment by imcwhinnie** [comment]
SPAMMING UNTIL YOU MERGE

**Comment by imcwhinnie** [comment]
Hurry up mate

**Comment by imcwhinnie** [comment]
Taking your time eh?

**Review by GavinMcWhinnie — APPROVED** [review]
Yes, ok if these don't work, you're fired....

**Pull request merged**
